name: "CI and Documentation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ===================================
  # Run Tests, Pre-Commit, and Coverage
  # ===================================
  tests:
    runs-on: ubuntu-latest
    name: Run tests and code coverage
    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup SSH keys to clone private repos
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Setup Python
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      # Intall requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install pyembree
      - name: Install pyembree
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper build-essential libembree-dev libtbb-dev
          wget https://github.com/embree/embree/releases/download/v2.17.7/embree-2.17.7.x86_64.linux.tar.gz
          tar -xzvf embree-2.17.7.x86_64.linux.tar.gz
          source embree-2.17.7.x86_64.linux/embree-vars.sh
          git clone git@github.com:scopatz/pyembree.git
          cd pyembree
          pip install Cython
          pip install .
          cd ..

      # Run Pytest
      - name: Run Pytest
        run: |
          pytest --timeout 60

