name: "CI and Documentation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ===================================
  # Run Tests, Pre-Commit, and Coverage
  # ===================================
  tests:
    runs-on: ubuntu-latest
    name: Run tests and code coverage
    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      # Intall requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install pyembree
      - name: Install pyembree
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper build-essential libembree-dev libtbb-dev
          wget https://github.com/embree/embree/releases/download/v2.17.7/embree-2.17.7.x86_64.linux.tar.gz
          tar -xzvf embree-2.17.7.x86_64.linux.tar.gz
          source embree-2.17.7.x86_64.linux/embree-vars.sh
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/embree-2.17.7.x86_64.linux/lib
          git clone https://github.com/scopatz/pyembree.git
          cd pyembree
          pip install numpy Cython wheel
          export SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0
          export PIP_USE_PEP517=0
          pip install . --no-build-isolation
          cd ..

      # Run Pytest
      - name: Run Pytest
        run: |
          pytest --timeout 60

